language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

node_js:
  - "0.11"
  - "0.12"
  - "iojs"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
